export default {
  items: [
    {
      name: "Andrea Jovine patterned wool blazer",
      category: "Jackets",
      id: "21",
      price: "23",
      size: "6",
      brand: "Andrea Jovine",
      url: "/img/andjovblazer.png",
      url1: "/img/andjovblazer1.png",
      url2: "/img/andjovblazer2.png",
      url3: "/img/andjovblazer3.png",
      description:
        "Very trendy Andrea Jovine patterned blazer. 100% wool. Very cute with plain outfit under. Functional pockets.",
    },
    {
      name: "LF black zip up cropped sweater",
      category: "Sweatshirts",
      id: "22",
      price: "35",
      size: "S",
      brand: "LF Seek",
      url: "/img/lfzipsweatshirt.png",
      url1: "/img/lfzipsweatshirt1.png",
      url2: "/img/lfzipsweatshirt2.png",
      url3: "/img/lfzipsweatshirt3.png",
      description:
        "LF Black zip up cropped sweater. Super cute and comfortable. Very trendy. Sweater can be zipped undone with a cute top underneath for style. Zippers light up with flash.",
    },
    {
      name: "Karen Kane red velvet dressy top",
      category: "Tops",
      id: "23",
      price: "19",
      size: "6",
      brand: "Karen Kane",
      url: "/img/karenkaneredvelvet.png",
      url1: "/img/karenkaneredvelvet1.png",
      url2: "/img/karenkaneredvelvet2.png",
      url3: "/img/karenkaneredvelvet3.png",
      description:
        "Karen Kane black and red dressy velvet sleeveless top. Super cute with zipper in the back. Perfect for the holidays. Best fits size small",
    },
    {
      name: "Reebok black track pants",
      category: "Bottoms",
      id: "24",
      price: "15",
      size: "M",
      brand: "Reebok",
      url: "/img/reeboktrack.png",
      url1: "/img/reeboktrack1.png",
      url2: "/img/reeboktrack2.png",
      url3: "/img/reeboktrack3.png",
      description:
        "Reebok Black pants with white stripe. Workout material. Super cute and comfortable. Men’s medium, but I’m a woman’s small and these fit me.",
    },
    {
      name: "Calvin Klein blue tshirt",
      category: "Tops",
      id: "1",
      price: "15",
      size: "Small",
      brand: "Calvin Klein",
      url: "/img/blueck.png",
      url1: "/img/blueck1.png",
      url2: "/img/blueck2.png",
      url3: "/img/blueck3.png",
      description:
        "Blue CK top. Can be tucked in, cropped, whatever! Very cute with light embroidered Calvin Klein.",
    },
    {
      name: "Black tight mini dress",
      category: "Dresses",
      id: "2",
      price: "15",
      size: "Small",
      brand: "Bloomingdales",
      url: "/img/blackdress.png",
      url1: "/img/blackdress1.png",
      url2: "/img/blackdress2.png",
      url3: "/img/blackdress3.png",
      description:
        "Tight little black dress, but very stretchy. Super cute for a night out. ",
    },
    {
      name: "Red adidas tank",
      category: "Tops",
      id: "3",
      price: "11",
      size: "Small",
      brand: "Adidas",
      url: "/img/redadd.png",
      url1: "/img/redadd1.png",
      url2: "/img/redadd2.png",
      url3: "/img/redadd3.png",
      description:
        "Red adidas tank. Super cute for working out or just hanging out. ",
    },
    {
      name: "Band tee",
      category: "Tops",
      id: "4",
      price: "13",
      size: "1X",
      brand: "Forever 21",
      url: "/img/bandtee.png",
      url1: "/img/bandtee1.png",
      url2: "/img/bandtee2.png",
      url3: "/img/bandtee3.png",
      description:
        "Band muscle tank. Cool design down the middle of the shirt. Fun and different!",
    },
    {
      name: "Yellow LF Top",
      category: "Tops",
      id: "5",
      price: "16",
      size: "Medium",
      brand: "LF/Emma and Sam",
      url: "/img/lftop.png",
      url1: "/img/lftop1.png",
      url2: "/img/lftop2.png",
      url3: "/img/lftop3.png",
      description:
        "Yellow long sleeve top with small holes in it for style. Super cute. Made by emma and sam but bought at LF. ",
    },
    {
      name: "Green Free People long sleeve top",
      category: "Tops",
      id: "6",
      price: "15",
      size: "Extra small",
      brand: "Free People",
      url: "/img/greenfp.png",
      url1: "/img/greenfp1.png",
      url2: "/img/greenfp2.png",
      url3: "/img/greenfp3.png",
      description:
        "Lime green long sleeve FP top with lace sleeves. Button down top and super cute!",
    },
    {
      name: "BillaBong Hoodie",
      category: "Sweatshirts",
      id: "7",
      price: "18",
      size: "Small",
      brand: "BillaBong",
      url: "/img/billabong.png",
      url1: "/img/billabong1.png",
      url2: "/img/billabong2.png",
      url3: "/img/billabong3.png",
      description:
        "BillaBong hoodie with pockets. Super cute. Different colored sleeves and rope string.",
    },
    {
      name: "LF Plaid Blazer",
      category: "Jackets",
      id: "8",
      price: "35",
      size: "Exra small",
      brand: "LF",
      url: "/img/lfblazer.png",
      url1: "/img/lfblazer1.png",
      url2: "/img/lfblazer2.png",
      url3: "/img/lfblazer3.png",
      description:
        "LF plaid blazer. Very trendy right now. Made by SEEK sold at LF.",
    },
    {
      name: "Tight red zip up jacket",
      category: "Jackets",
      id: "9",
      price: "13",
      size: "Small",
      brand: "San Francisco City Lights",
      url: "/img/redjack.png",
      url1: "/img/redjack1.png",
      url2: "/img/redjack2.png",
      url3: "/img/redjack3.png",
      description:
        "Tight cherry red zip up jacket with gold zipper. Super cute.",
    },
    {
      name: "The Beatles crop top",
      category: "Tops",
      id: "10",
      price: "11",
      size: "Small",
      brand: "The Beatles",
      url: "/img/beatlestop.png",
      url1: "/img/beatlestop1.png",
      url2: "/img/beatlestop2.png",
      url3: "/img/beatlestop3.png",
      description: "Authentic Beatles crop top tank. ",
    },
    {
      name: "Tie dye tee",
      category: "Tops",
      id: "11",
      price: "12",
      size: "Small",
      brand: "No brand",
      url: "/img/tiedye.png",
      url1: "/img/tiedye.png",
      url2: "/img/tiedye2.png",
      url3: "/img/tiedye3.png",
      description: "In right now, tie dye top. Very colorful and fun.",
    },
    {
      name: "Victoria's Secret PINK gray tunic",
      category: "Tops",
      id: "12",
      price: "13",
      size: "Extra Small",
      brand: "Victoria's Secret PINK",
      url: "/img/pinktunic.png",
      url1: "/img/pinktunic1.png",
      url2: "/img/pinktunic2.png",
      url3: "/img/pinktunic3.png",
      description: "Gray vs pink tunic. Super cute for a night out.",
    },
    {
      name: "White romper",
      category: "Dresses",
      id: "13",
      price: "13",
      size: "Small",
      brand: "Forever 21",
      url: "/img/whiteromper.png",
      url1: "/img/whiteromper1.png",
      url2: "/img/whiteromper2.png",
      url3: "/img/whiteromper3.png",
      description: "Beautiful white romper with adjustable straps. Lace top. ",
    },
    {
      name: "Amanda Richard Blouse",
      category: "Tops",
      id: "14",
      price: "22",
      size: "Small",
      brand: "Amanda Richard ",
      url: "/img/arblouse.png",
      url1: "/img/arblouse1.png",
      url2: "/img/arblouse2.png",
      url3: "/img/arblouse3.png",
      description:
        "Very nice, new with tags Amanda Richard blouse. Super cute with a pair of jeans!",
    },
    {
      name: "LF Black Soft Shorts",
      category: "Bottoms",
      id: "15",
      price: "19",
      size: "Small",
      brand: "LF",
      url: "/img/lfshorts.png",
      url1: "/img/lfshorts1.png",
      url2: "/img/lfshorts2.png",
      url3: "/img/lfshorts3.png",
      description:
        "Super cute LF shorts with stretchy waist band and pockets. LF tape for design. Very comfortable and trendy. ",
    },
    {
      name: "Juicy Black Dress",
      category: "Dresses",
      id: "16",
      price: "14",
      size: "Small",
      brand: "Juicy ",
      url: "/img/blackjuicy.png",
      url1: "/img/blackjuicy1.png",
      url2: "/img/blackjuicy2.png",
      url3: "/img/blackjuicy3.png",
      description:
        "Adorable little black dress. Lace bottom, mini pockets, and decorative straps.",
    },
    {
      name: "Floral Little Black Dress",
      category: "Dresses",
      id: "17",
      price: "29",
      size: "2",
      brand: "DK",
      url: "/img/blackfloral.png",
      url1: "/img/blackfloral1.png",
      url2: "/img/blackfloral2.png",
      url3: "/img/blackfloral3.png",
      description: "Floral slim little black dress. Very flattering.",
    },
    {
      name: "Blue and white tie-dye tank",
      category: "Tops",
      id: "18",
      price: "12",
      size: "S",
      brand: "No brand",
      url: "/img/bluescrunch.png",
      url1: "/img/bluescrunch1.png",
      url2: "/img/bluescrunch2.png",
      url3: "/img/bluescrunch3.png",
      description:
        "Tie dye denim blue scrunchy tank top. One-of-a-kind. Super cute and fun and perfect for any event! Very trendy right now:) . Never worn before and brand new.",
    },
    {
      name: "LF black scrunch mid sleeve top",
      category: "Tops",
      id: "19",
      price: "19",
      size: "S",
      brand: "LF",
      url: "/img/lfblckscrunch.png",
      url1: "/img/lfblckscrunch1.png",
      url2: "/img/lfblckscrunch2.png",
      url3: "/img/lfblckscrunch3.png",
      description:
        "Super cute and only worn once black LF crop top. There is a scrunch in the middle and ties at the bottom. The sleeves go halfway down arms. Super cute and unique.",
    },
    {
      name: "NWT Forever 21 Black long sleev vneck",
      category: "Tops",
      id: "20",
      price: "9",
      size: "S",
      brand: "Forever 21",
      url: "/img/f21blcklongsleeve.png",
      url1: "/img/f21blcklongsleeve1.png",
      url2: "/img/f21blcklongsleeve2.png",
      url3: "/img/f21blcklongsleeve3.png",
      description:
        "New with tags forever 21 black long sleeve V-neck. Super cute and fun and perfect for any event. Size medium but could fit a small.",
    },
  ],
  navs: [
    {
      name: "Tops",
    },
    {
      name: "Sweatshirts",
    },
    {
      name: "Jackets",
    },
    {
      name: "Bottoms",
    },
    {
      name: "Dresses",
    },
  ],
};
