export default {
  items: [
    {
      name: "Andrea Jovine patterned wool blazer",
      category: "Jackets",
      id: "1",
      price: "23",
      size: "6",
      brand: "Andrea Jovine",
      url: "/img/andjovblazer.png",
      url1: "/img/andjovblazer1.png",
      url2: "/img/andjovblazer2.png",
      url3: "/img/andjovblazer3.png",
      description:
        "Very trendy Andrea Jovine patterned blazer. 100% wool. Very cute with plain outfit under. Functional pockets.",
    },
    {
      name: "LF black zip up cropped sweater",
      category: "Sweatshirts",
      id: "2",
      price: "35",
      size: "S",
      brand: "LF Seek",
      url: "/img/lfzipsweatshirt.png",
      url1: "/img/lfzipsweatshirt1.png",
      url2: "/img/lfzipsweatshirt2.png",
      url3: "/img/lfzipsweatshirt3.png",
      description:
        "LF Black zip up cropped sweater. Super cute and comfortable. Very trendy. Sweater can be zipped undone with a cute top underneath for style. Zippers light up with flash.",
    },
    {
      name: "Red Champion Crewneck Sweatshirt",
      category: "Sweatshirts",
      id: "3",
      price: "33",
      size: "XL",
      brand: "Champion",
      url: "/img/redChampJack2.png",
      url1: "/img/redChampJack1.png",
      url2: "/img/redChampJack.png",
      url3: "/img/redChampJack3.png",
      description:
        "Super cute red champion crew neck sweatshirt. I wear it as an oversized sweatshirt. Love the color and it’s super comfortable.",
    },
    {
      name: "Blue Champion Crewneck Sweatshirt",
      category: "Sweatshirts",
      id: "4",
      price: "33",
      size: "XL",
      brand: "Champion",
      url: "/img/blueChampJack.png",
      url1: "/img/blueChampJack1.png",
      url2: "/img/blueChampJack2.png",
      url3: "/img/blueChampJack3.png",
      description:
        "Super cute blue champion crew neck sweatshirt. I wear it as an oversized sweatshirt. Love the color and it’s super comfortable.",
    },
    {
      name: "Karen Kane red velvet dressy top",
      category: "Tops",
      id: "5",
      price: "19",
      size: "6",
      brand: "Karen Kane",
      url: "/img/karenkaneredvelvet.png",
      url1: "/img/karenkaneredvelvet1.png",
      url2: "/img/karenkaneredvelvet2.png",
      url3: "/img/karenkaneredvelvet3.png",
      description:
        "Karen Kane black and red dressy velvet sleeveless top. Super cute with zipper in the back. Perfect for the holidays. Best fits size small",
    },
    {
      name: "Calvin Klein blue tshirt",
      category: "Tops",
      id: "6",
      price: "15",
      size: "Small",
      brand: "Calvin Klein",
      url: "/img/blueck.png",
      url1: "/img/blueck1.png",
      url2: "/img/blueck2.png",
      url3: "/img/blueck3.png",
      description:
        "Blue CK top. Can be tucked in, cropped, whatever! Very cute with light embroidered Calvin Klein.",
    },
    {
      name: "Red adidas tank",
      category: "Tops",
      id: "7",
      price: "11",
      size: "Small",
      brand: "Adidas",
      url: "/img/redadd.png",
      url1: "/img/redadd1.png",
      url2: "/img/redadd2.png",
      url3: "/img/redadd3.png",
      description:
        "Red adidas tank. Super cute for working out or just hanging out. ",
    },
    {
      name: "Carmar LF ripped white jeans",
      category: "Bottoms",
      id: "8",
      price: "59",
      size: "26",
      brand: "LF Carmar",
      url: "/img/whitelfpants.png",
      url1: "/img/whitelfpants1.png",
      url2: "/img/whitelfpants2.png",
      url3: "/img/whitelfpants3.png",
      description:
        "Only worn a few times high waisted ripped white jeans made by carmar and sold at LF. Super cute with huge rips. Very trendy. Got so many compliments the few times I wore these. ",
    },
    {
      name: "Green Free People long sleeve top",
      category: "Tops",
      id: "9",
      price: "15",
      size: "Extra small",
      brand: "Free People",
      url: "/img/greenfp.png",
      url1: "/img/greenfp1.png",
      url2: "/img/greenfp2.png",
      url3: "/img/greenfp3.png",
      description:
        "Lime green long sleeve FP top with lace sleeves. Button down top and super cute!",
    },
    {
      name: "BillaBong Hoodie",
      category: "Sweatshirts",
      id: "10",
      price: "18",
      size: "Small",
      brand: "BillaBong",
      url: "/img/billabong.png",
      url1: "/img/billabong1.png",
      url2: "/img/billabong2.png",
      url3: "/img/billabong3.png",
      description:
        "BillaBong hoodie with pockets. Super cute. Different colored sleeves and rope string.",
    },
    {
      name: "LF Plaid Blazer",
      category: "Jackets",
      id: "11",
      price: "35",
      size: "Exra small",
      brand: "LF",
      url: "/img/lfblazer.png",
      url1: "/img/lfblazer1.png",
      url2: "/img/lfblazer2.png",
      url3: "/img/lfblazer3.png",
      description:
        "LF plaid blazer. Very trendy right now. Made by SEEK sold at LF.",
    },
    {
      name: "The Beatles crop top",
      category: "Tops",
      id: "12",
      price: "11",
      size: "Small",
      brand: "The Beatles",
      url: "/img/beatlestop.png",
      url1: "/img/beatlestop1.png",
      url2: "/img/beatlestop2.png",
      url3: "/img/beatlestop3.png",
      description: "Authentic Beatles crop top tank. ",
    },
    {
      name: "Victoria's Secret PINK gray tunic",
      category: "Tops",
      id: "13",
      price: "13",
      size: "Extra Small",
      brand: "Victoria's Secret PINK",
      url: "/img/pinktunic.png",
      url1: "/img/pinktunic1.png",
      url2: "/img/pinktunic2.png",
      url3: "/img/pinktunic3.png",
      description: "Gray vs pink tunic. Super cute for a night out.",
    },
    {
      name: "Lucky Brand dark blue jeans",
      category: "Bottoms",
      id: "14",
      price: "17",
      size: "25",
      brand: "Lucky Brand",
      url: "/img/luckyBrandJeans.png",
      url1: "/img/luckyBrandJeans1.png",
      url2: "/img/luckyBrandJeans2.png",
      url3: "/img/luckyBrandJeans3.png",
      description:
        "Amazing condition lucky brand ripped blue jeans. These are the most beautiful color and so cute. They have rips in the knees and under the butt. very stretchy and soft material.",
    },
    {
      name: "White romper",
      category: "Dresses",
      id: "15",
      price: "13",
      size: "Small",
      brand: "Forever 21",
      url: "/img/whiteromper.png",
      url1: "/img/whiteromper1.png",
      url2: "/img/whiteromper2.png",
      url3: "/img/whiteromper3.png",
      description: "Beautiful white romper with adjustable straps. Lace top. ",
    },
    {
      name: "Amanda Richard Blouse",
      category: "Tops",
      id: "16",
      price: "22",
      size: "Small",
      brand: "Amanda Richard ",
      url: "/img/arblouse.png",
      url1: "/img/arblouse1.png",
      url2: "/img/arblouse2.png",
      url3: "/img/arblouse3.png",
      description:
        "Very nice, new with tags Amanda Richard blouse. Super cute with a pair of jeans!",
    },
    {
      name: "LF Black Soft Shorts",
      category: "Bottoms",
      id: "17",
      price: "19",
      size: "Small",
      brand: "LF",
      url: "/img/lfshorts.png",
      url1: "/img/lfshorts1.png",
      url2: "/img/lfshorts2.png",
      url3: "/img/lfshorts3.png",
      description:
        "Super cute LF shorts with stretchy waist band and pockets. LF tape for design. Very comfortable and trendy. ",
    },
    {
      name: "Blue and white tie-dye tank",
      category: "Tops",
      id: "18",
      price: "12",
      size: "S",
      brand: "No brand",
      url: "/img/bluescrunch.png",
      url1: "/img/bluescrunch1.png",
      url2: "/img/bluescrunch2.png",
      url3: "/img/bluescrunch3.png",
      description:
        "Tie dye denim blue scrunchy tank top. One-of-a-kind. Super cute and fun and perfect for any event! Very trendy right now:) . Never worn before and brand new.",
    },
    {
      name: "LF NWT ripped blue jean beatrice skirt",
      category: "Bottoms",
      id: "19",
      price: "35",
      size: "24",
      brand: "LF Carmar Denim",
      url: "/img/lfRippedSkirtJean1.png",
      url1: "/img/lfRippedSkirtJean.png",
      url2: "/img/lfRippedSkirtJean2.png",
      url3: "/img/lfRippedSkirtJean3.png",
      description:
        "New with tags, never worn LF Beatrice denim ripped skirt. Made by carmar. The cutest skirt ever. Very trendy and perfect for any event. Originally $178.",
    },
    {
      name: "LF black scrunch mid sleeve top",
      category: "Tops",
      id: "20",
      price: "19",
      size: "S",
      brand: "LF",
      url: "/img/lfblckscrunch.png",
      url1: "/img/lfblckscrunch1.png",
      url2: "/img/lfblckscrunch2.png",
      url3: "/img/lfblckscrunch3.png",
      description:
        "Super cute and only worn once black LF crop top. There is a scrunch in the middle and ties at the bottom. The sleeves go halfway down arms. Super cute and unique.",
    },
    {
      name: "NWT Forever 21 Black long sleev vneck",
      category: "Tops",
      id: "21",
      price: "9",
      size: "S",
      brand: "Forever 21",
      url: "/img/f21blcklongsleeve.png",
      url1: "/img/f21blcklongsleeve1.png",
      url2: "/img/f21blcklongsleeve2.png",
      url3: "/img/f21blcklongsleeve3.png",
      description:
        "New with tags forever 21 black long sleeve V-neck. Super cute and fun and perfect for any event. Size medium but could fit a small.",
    },
    {
      name: "NWOT LF Black and White Tie Dye Jeans",
      category: "Bottoms",
      id: "22",
      price: "38",
      size: "26",
      brand: "LF Carmar Denim",
      url: "/img/LfBlackAndWhiteTieDyeJeans.png",
      url1: "/img/LfBlackAndWhiteTieDyeJeans1.png",
      url2: "/img/LfBlackAndWhiteTieDyeJeans2.png",
      url3: "/img/LfBlackAndWhiteTieDyeJeans3.png",
      description:
        "Great condition - only worn once. Super rare. Originally $228. Made by carmar denim. Size 26 but prob fits a 25 better.",
    },
    {
      name: "Light pink and white tie-dye tank top",
      category: "Tops",
      id: "23",
      price: "13",
      size: "Small",
      brand: "No brand",
      url: "/img/pinkAndWhiteTieDyeTank.png",
      url1: "/img/pinkAndWhiteTieDyeTank1.png",
      url2: "/img/pinkAndWhiteTieDyeTank2.png",
      url3: "/img/pinkAndWhiteTieDyeTank3.png",
      description:
        "Tie dye pink scrunch tank top. One-of-a-kind. Super cute and fun and perfect for any event! Very trendy right now:) under brandy for exposure. Never worn before and brand new! First two pics are not mine",
    },
  ],
  navs: [
    {
      name: "Tops",
    },
    {
      name: "Sweatshirts",
    },
    {
      name: "Jackets",
    },
    {
      name: "Bottoms",
    },
    {
      name: "Dresses",
    },
  ],
};
